FROM ubuntu:latest
RUN apt-get update && apt-get upgrade -y
RUN apt install -y libgtest-dev
RUN apt-get install -y libgmock-dev
RUN apt-get install -y cmake
RUN apt-get install -y make
RUN apt-get install -y valgrind --fix-missing
RUN apt-get install -y g++
RUN apt-get install -y libncurses5-dev
